name: Green Commit Automation

on:
  schedule:
    # Evening coding session (8-10 PM Bangladesh) = 2-4 PM UTC
    - cron: '35 14,15,16 * * 1-5'
    # Late night coding (11 PM - 1 AM Bangladesh) = 5-7 PM UTC
    - cron: '15 17,18,19 * * 1-5'
    # Weekend late nights (10 PM - 2 AM Bangladesh) = 4-8 PM UTC
    - cron: '42 16,17,18,19,20 * * 0,6'
  workflow_dispatch:

# Add permissions block
permissions:
  contents: write

jobs:
  green-commits:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Dhaka'  # Set timezone to Bangladesh

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytz

    - name: Configure Git
      run: |
        git config --global user.name "waliulrayhan"
        git config --global user.email "b190305034@cse.jnu.ac.bd"
        git config pull.rebase false

    - name: Sync with remote
      run: |
        git pull origin main

    - name: Make realistic random commits
      run: |
        python green_commit.py
        cat activity.log

    - name: Commit and Push
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        # Configure Git with token
        git remote set-url origin "https://${{ github.actor }}:${TOKEN}@github.com/${{ github.repository }}.git"
        
        # Add and commit changes
        git add activity.log
        
        if git diff --cached --quiet; then
          echo "No changes to commit"
          exit 0
        else
          # Get the commit message from the last line of activity.log
          COMMIT_MSG=$(tail -n 1 activity.log)
          echo "Committing with message: $COMMIT_MSG"
          
          # Commit and push
          git commit -m "$COMMIT_MSG"
          
          # Try to push, if fails, pull and push again
          git push origin main || {
            git pull origin main
            git push origin main
          }
        fi
