name: Green Commit Automation

on:
  schedule:
    - cron: '7 9 * * *'
    - cron: '42 13 * * *'
    - cron: '25 20 * * *'
  workflow_dispatch:

jobs:
  green-commits:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Make realistic random commits
      run: |
        python green_commit.py

    - name: Push changes
      run: |
        git config user.name "waliulrayhan"
        git config user.email "b190305034@cse.jnu.ac.bd"
        git push
