name: Green Commit Automation

on:
  schedule:
    # Early morning (5-9 AM) - random minutes
    - cron: '12 5-9 * * 1-5'
    # Lunch time (12-2 PM) - random minutes
    - cron: '42 12-14 * * 1-5'
    # Evening (6-9 PM) - random minutes
    - cron: '27 18-21 * * 1-5'
    # Weekend random times
    - cron: '15 10-16 * * 0,6'
  workflow_dispatch:

jobs:
  green-commits:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Configure Git
      run: |
        git config --global user.name "waliulrayhan"
        git config --global user.email "b190305034@cse.jnu.ac.bd"
        git config pull.rebase false

    - name: Sync with remote
      run: |
        git pull origin main

    - name: Make realistic random commits
      run: |
        python green_commit.py
        cat activity.log

    - name: Commit and Push
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        # Configure Git with token
        git remote set-url origin "https://${{ github.actor }}:${PERSONAL_TOKEN}@github.com/${{ github.repository }}.git"
        
        # Add and commit changes
        git add activity.log
        
        if git diff --cached --quiet; then
          echo "No changes to commit"
          exit 0
        else
          # Get the commit message from the last line of activity.log
          COMMIT_MSG=$(tail -n 1 activity.log)
          echo "Committing with message: $COMMIT_MSG"
          
          # Commit and push
          git commit -m "$COMMIT_MSG"
          
          # Try to push, if fails, pull and push again
          git push origin main || {
            git pull origin main
            git push origin main
          }
        fi
