name: Green Commit Automation

on:
  schedule:
    - cron: '7 9 * * *'
    - cron: '42 13 * * *'
    - cron: '25 20 * * *'
  workflow_dispatch:

jobs:
  green-commits:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Make realistic random commits
      run: |
        python green_commit.py

    - name: Configure Git
      run: |
        git config --global user.name "waliulrayhan"
        git config --global user.email "b190305034@cse.jnu.ac.bd"

    - name: Push changes
      run: |
        git add .
        git commit -m "Automated commit: $(date)"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
