name: Green Commit Automation

on:
  schedule:
    # Early morning (5-9 AM) - random minutes
    - cron: '12 5-9 * * 1-5'
    # Lunch time (12-2 PM) - random minutes
    - cron: '42 12-14 * * 1-5'
    # Evening (6-9 PM) - random minutes
    - cron: '27 18-21 * * 1-5'
    # Weekend random times
    - cron: '15 10-16 * * 0,6'
  workflow_dispatch:

jobs:
  green-commits:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Debug Info
      run: |
        echo "Repository: ${{ github.repository }}"
        echo "Checking repository visibility..."
        curl -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
             -H "Accept: application/vnd.github.v3+json" \
             https://api.github.com/repos/${{ github.repository }}

    - name: Make realistic random commits
      run: |
        python green_commit.py

    - name: Configure Git and Push
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        git config --global user.name "waliulrayhan"
        git config --global user.email "b190305034@cse.jnu.ac.bd"
        
        # Configure Git with token
        git remote set-url origin "https://${{ github.actor }}:${PERSONAL_TOKEN}@github.com/${{ github.repository }}.git"
        
        # Ensure we're on the main branch
        git checkout main
        
        # Pull latest changes
        git pull origin main --rebase
        
        # Add and commit changes
        git add activity.log
        git status
        
        if git diff --staged --quiet; then
          echo "No changes to commit"
          exit 0
        else
          git commit -m "Automated commit: $(date)"
          # Force push with lease for safety
          git push --force-with-lease origin main
        fi
