name: Green Commit Automation

on:
  schedule:
    - cron: '7 9 * * *'
    - cron: '42 13 * * *'
    - cron: '25 20 * * *'
  workflow_dispatch:

jobs:
  green-commits:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Debug Info
      run: |
        echo "GitHub Actor: ${{ github.actor }}"
        echo "Repository: ${{ github.repository }}"
        git config --list

    - name: Make realistic random commits
      run: |
        python green_commit.py

    - name: Configure Git and Push
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git config --global user.name "waliulrayhan"
        git config --global user.email "b190305034@cse.jnu.ac.bd"
        git remote set-url origin https://waliulrayhan:${PAT_TOKEN}@github.com/waliulrayhan/greener.git
        git add activity.log
        git status
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Automated commit: $(date)"
          git push
        fi
