name: Green Commit Automation

on:
  schedule:
    # Early morning (5-9 AM) - random minutes
    - cron: '12 5-9 * * 1-5'
    # Lunch time (12-2 PM) - random minutes
    - cron: '42 12-14 * * 1-5'
    # Evening (6-9 PM) - random minutes
    - cron: '27 18-21 * * 1-5'
    # Weekend random times
    - cron: '15 10-16 * * 0,6'
  workflow_dispatch:

permissions:
  contents: write
  actions: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  green-commits:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        persist-credentials: false
        fetch-depth: 0
        token: ${{ secrets.GH_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Debug Info
      run: |
        echo "Repository: ${{ github.repository }}"
        git config --list

    - name: Make realistic random commits
      run: |
        python green_commit.py

    - name: Configure Git and Push
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global user.name "waliulrayhan"
        git config --global user.email "b190305034@cse.jnu.ac.bd"
        
        git remote set-url origin https://oauth2:${GH_TOKEN}@github.com/waliulrayhan/greener.git
        
        # Fetch and rebase before pushing
        git fetch origin main
        git rebase origin/main
        
        git add activity.log
        git status
        
        if git diff --staged --quiet; then
          echo "No changes to commit"
          exit 0
        else
          git commit -m "Automated commit: $(date)"
          git push origin HEAD:main || {
            # If push fails, try pulling and pushing again
            git pull --rebase origin main
            git push origin HEAD:main
          }
        fi
